root: true
parserOptions:
  ecmaVersion: 2017
env:
  browser: true
  node: true
  es6: true
extends:
  - eslint:recommended
rules:
  prefer-const: error
  no-console: warn
  func-names: off
  prefer-arrow-callback: error
  no-process-exit: off
  object-shorthand: off
  spaced-comment: error
  class-methods-use-this: error
  no-duplicate-imports: error
  camelcase: error
  capitalized-comments:
    - error
    - never
  no-else-return: error
  complexity:
    - error
    - 4
  dot-notation: error
  func-style:
    - error
    - expression
  max-depth:
    - error
    - 3
  wrap-iife:
    - error
    - outside
  no-loop-func: error
  arrow-parens:
    - error
    - always
  prefer-rest-params: error
  default-param-last: error
  no-new-func: error
  space-before-function-paren:
    - error
    - always
  space-before-blocks:
    - error
    - always
  no-param-reassign: error
  prefer-spread: error
  function-paren-newline:
    - error
    - minItems: 3
